### ISSUE TITLE
Github CI?

### ISSUE THREAD

**Issue by DartPower** [ferib/D2R-Offline#52]
Can you make the Actions (Github CI) script? 
e.g. for release and/or beta automatic builds

**Comment by ferib** [comment]
This is not a bad idea, maybe some GitHub Actions on the `Master` branch.
I have little to no experience with these GitHub Actions, so if anyone here wants to do this, feel free to PR.

**Comment by DartPower** [comment]
I have some experience, i will try and do the pull request :)

**Comment by DartPower** [comment]
Can you manually add the workflow file? :)
I'm have very bad experience with pull requests :( 

`D2R-Offline/.github/workflows/nightly.yml`

```
name: nightly

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  nightly:
    runs-on: windows-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5
    - name: Restore dependencies 
      run: nuget restore .
    - name: Build
      run: msbuild /p:Configuration=Release
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.3
      with:
        path: D:\a\D2R-Offline\D2R-Offline\src\bin\Release\
```

Also info:
1. This also may stuck on "Starting workflow run" but need to wait 10-15 mins. (Me have this bug, i think this is Github servers problems)
2. This is simply "duct tape". (e.g. non-realitive path in artifact uploader and etc)
